### 常见的tensor形式有哪些
+ 0:scalr
+ 1:vector
+ 2:matrix
+ 3:n-dimensional tensor


### scalr
通常就是一个数值

In [2]:
import torch
from torch import tensor

In [3]:
x=tensor(42.)
x

tensor(42.)

In [4]:
x.dim()

0

In [5]:
x.item()

42.0

### Vector

In [6]:
v=tensor([1.5,-0.5,3.0])

In [7]:
v

tensor([ 1.5000, -0.5000,  3.0000])

In [8]:
v.dim()

1

In [9]:
v.size()

torch.Size([3])

### Matrix

In [10]:
m=tensor([[1.,2.],[3.,4.]])
m

tensor([[1., 2.],
        [3., 4.]])

In [11]:
m.matmul(m) # 矩阵乘法

tensor([[ 7., 10.],
        [15., 22.]])

### n-D tensor